# Generated by Django 4.2.1 on 2023-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.IntegerField(null=True, verbose_name='Почтовый индекс')),
                ('lat', models.CharField(max_length=20, null=True, verbose_name='Широта')),
                ('lng', models.CharField(max_length=20, null=True, verbose_name='Долгота')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='Город')),
                ('state_name', models.CharField(max_length=30, null=True, verbose_name='Штат')),
            ],
        ),
    ]
