# Generated by Django 4.2.1 on 2023-05-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='uploads/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
