# Generated by Django 4.2.1 on 2023-05-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_locationimport_alter_location_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='LocationImport',
        ),
    ]
