# Generated by Django 4.2.1 on 2023-05-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationimport',
            old_name='csv_file',
            new_name='file',
        ),
    ]
