# Generated by Django 4.2.1 on 2023-05-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_rename_csv_file_locationimport_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='LocationImport',
        ),
    ]
