# Generated by Django 4.2.1 on 2023-05-27 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('zip', models.IntegerField()),
                ('load_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_pickup', models.IntegerField()),
                ('zip_delivery', models.IntegerField()),
                ('cargo', models.FloatField()),
                ('description', models.TextField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.truck')),
            ],
        ),
    ]
